/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserRoleIndexRouteImport } from './routes/$userRole/index'
import { Route as UserRoleCoursesSplatRouteImport } from './routes/$userRole/courses.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoleIndexRoute = UserRoleIndexRouteImport.update({
  id: '/$userRole/',
  path: '/$userRole/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoleCoursesSplatRoute = UserRoleCoursesSplatRouteImport.update({
  id: '/$userRole/courses/$',
  path: '/$userRole/courses/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$userRole/': typeof UserRoleIndexRoute
  '/$userRole/courses/$': typeof UserRoleCoursesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$userRole': typeof UserRoleIndexRoute
  '/$userRole/courses/$': typeof UserRoleCoursesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$userRole/': typeof UserRoleIndexRoute
  '/$userRole/courses/$': typeof UserRoleCoursesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$userRole/' | '/$userRole/courses/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$userRole' | '/$userRole/courses/$'
  id: '__root__' | '/' | '/$userRole/' | '/$userRole/courses/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoleIndexRoute: typeof UserRoleIndexRoute
  UserRoleCoursesSplatRoute: typeof UserRoleCoursesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userRole/': {
      id: '/$userRole/'
      path: '/$userRole'
      fullPath: '/$userRole/'
      preLoaderRoute: typeof UserRoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userRole/courses/$': {
      id: '/$userRole/courses/$'
      path: '/$userRole/courses/$'
      fullPath: '/$userRole/courses/$'
      preLoaderRoute: typeof UserRoleCoursesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoleIndexRoute: UserRoleIndexRoute,
  UserRoleCoursesSplatRoute: UserRoleCoursesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
